apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neon.fullname" . }}-pageserver
  labels:
    {{- include "neon.pageserver.labels" . | nindent 4 }}
data:
  pageserver.toml: |
    listen_http_addr = "0.0.0.0:9898"
    listen_pg_addr = "0.0.0.0:64000"
    broker_endpoint = "http://{{ include "neon.fullname" . }}-storage-broker"
    pg_distrib_dir = "/usr/local/v15"

    [remote_storage]
    {{- with .Values.remoteStorage.endpoint }}
    endpoint = "{{ . }}"
    {{- end }}
    bucket_name = "{{ .Values.remoteStorage.bucket.name }}"
    bucket_region = "{{ .Values.remoteStorage.bucket.region }}"
    {{- with .Values.remoteStorage.bucket.prefix }}
    prefix_in_bucket = "{{ . }}"
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neon.fullname" . }}-pageserver
  labels:
    {{- include "neon.pageserver.labels" . | nindent 4 }}
  {{- with .Values.pageserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "neon.fullname" . }}-pageserver
  labels:
    {{- include "neon.pageserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "neon.pageserver.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pageserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neon.pageserver.labels" . | nindent 8 }}
        {{- with .Values.pageserver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "neon.fullname" . }}-pageserver
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: storage-broker-wait
        image: busybox:1.28
        command: 
        - sh
        - -c
        - |
          until wget -O - http://{{ include "neon.fullname" . }}-storage-broker/status
          do echo waiting for storage-broker
          sleep 2
          done
      containers:
      - name: pageserver
        image: {{ .Values.pageserver.image.repository }}:{{ .Values.pageserver.image.tag }}
        imagePullPolicy: {{ .Values.pageserver.image.pullPolicy }}
        command: 
        - sh
        - -c
        - |
          pageserver \
            -D /data/.neon/ \
            -c id=${HOSTNAME##*-}
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: pg
          containerPort: 64000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /v1/status
            port: http
        resources:
          {{- toYaml .Values.pageserver.resources | nindent 12 }}
        volumeMounts:
        - name: pageserver-config
          mountPath: /data/.neon/pageserver.toml
          subPath: pageserver.toml
        - name: pageserver-data
          mountPath: /data/.neon
      volumes:
      - name: pageserver-config
        configMap:
          name: {{ include "neon.fullname" . }}-pageserver
          items:
          - key: pageserver.toml
            path: pageserver.toml
      - name: pageserver-data
        persistentVolumeClaim:
          claimName: {{ include "neon.fullname" . }}-pageserver
      {{- with .Values.pageserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pageserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pageserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon.fullname" . }}-pageserver
  labels:
    {{- include "neon.pageserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "neon.pageserver.labels" . | nindent 4 }}
  ports:
  - name: http
    targetPort: http
    protocol: TCP
    port: 80
  - name: pg
    targetPort: pg
    protocol: TCP
    port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neon.fullname" . }}-pageserver
  labels:
    {{- include "neon.pageserver.labels" . | nindent 4 }}
spec:
  {{- with .Values.pageserver.storage.className }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pageserver.storage.capacity }}
