nameOverride: ""
fullnameOverride: ""

remoteStorage:
  endpoint:
  bucket:
    name: ""
    region: ""
    prefix:

pageserver:
  image:
    repository: neondatabase/neon
    pullPolicy: Always
    tag: latest
  podAnnotations: {}
  podLabels: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    annotations: {}
  storage:
    className:
    capacity: 1Gi

safekeeper:
  image:
    repository: neondatabase/neon
    pullPolicy: Always
    tag: latest
  podAnnotations: {}
  podLabels: {}
  resources: {}
  serviceAccount:
    annotations: {}
  storage:
    className:
    capacity: 1Gi

storageBroker:
  image:
    repository: neondatabase/neon
    pullPolicy: Always
    tag: latest
  podAnnotations: {}
  podLabels: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
