apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neon-compute.fullname" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
data:
  spec.json: |
    {
      "format_version": 1.0,
      "pageserver_connstring": "{{ .Values.pageserver.connstring }}",
      "safekeeper_connstrings": {{ .Values.safekeeper.connstrings | toJson }},
      "tenant_id": "{{ .Values.tenantId }}",
      "timeline_id": "{{ .Values.timelineId }}",
      "cluster": {
        "roles": [],
        "databases": [],
        "settings": [
          {
              "name": "listen_addresses",
              "value": "0.0.0.0",
              "vartype": "string"
          },
          {
              "name": "max_wal_senders",
              "value": "10",
              "vartype": "integer"
          },
          {
              "name": "wal_log_hints",
              "value": "on",
              "vartype": "bool"
          },
          {
              "name": "max_replication_slots",
              "value": "10",
              "vartype": "integer"
          },
          {
              "name": "hot_standby",
              "value": "on",
              "vartype": "bool"
          },
          {
              "name": "shared_buffers",
              "value": "1MB",
              "vartype": "string"
          },
          {
              "name": "fsync",
              "value": "off",
              "vartype": "bool"
          },
          {
              "name": "max_connections",
              "value": "100",
              "vartype": "integer"
          },
          {
              "name": "wal_level",
              "value": "logical",
              "vartype": "enum"
          },
          {
              "name": "wal_sender_timeout",
              "value": "5s",
              "vartype": "string"
          },
          {
              "name": "wal_keep_size",
              "value": "0",
              "vartype": "integer"
          },
          {
              "name": "restart_after_crash",
              "value": "off",
              "vartype": "bool"
          },
          {
              "name": "shared_preload_libraries",
              "value": "neon",
              "vartype": "string"
          },
          {
              "name": "max_replication_write_lag",
              "value": "500MB",
              "vartype": "string"
          },
          {
              "name": "max_replication_flush_lag",
              "value": "10GB",
              "vartype": "string"
          },
          {
              "name": "synchronous_standby_names",
              "value": "walproposer",
              "vartype": "string"
          }
        ]
      }
    }
