apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neon-compute.fullname" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
data:
  spec.json: |
    {
      "format_version": 1.0,
      "pageserver_connstring": "{{ .Values.pageserver.connstring }}",
      "safekeeper_connstrings": {{ .Values.safekeeper.connstrings | toJson }},
      "tenant_id": "{{ .Values.tenantId }}",
      "timeline_id": "{{ .Values.timelineId }}",
      "cluster": {
        "roles": [],
        "databases": [],
        "settings": [
          {
              "name": "listen_addresses",
              "value": "0.0.0.0",
              "vartype": "string"
          }
        ]
      }
    }
