apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neon-compute.fullname" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "neon-compute.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neon-compute.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: compute-node
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: 
        - sh
        - -c
        - |
          compute_ctl \
            --pgdata=/var/db/postgres/compute \
            --connstr=postgresql://cloudadmin@0.0.0.0:5432/postgres \
            --pgbin=/usr/local/bin/postgres \
            --spec-path=/tmp/spec.json
        env:
        - name: OTEL_SDK_DISABLED
          value: "true"
        ports:
        - name: http
          containerPort: 3080
          protocol: TCP
        - name: pg
          containerPort: 5432
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: compute-node-spec
          mountPath: /tmp/spec.json
          subPath: spec.json
      volumes:
      - name: compute-node-spec
        configMap:
          name: {{ include "neon-compute.fullname" . }}
          items:
          - key: spec.json
            path: spec.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
