apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-compute.fullname" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
type: Opaque
data:
  connstr_username: {{ .Values.auth.username | b64enc }}
  {{- with .Values.auth.password }}
  connstr_password: {{ . | b64enc }}
  {{- end }}
  connstr_database: {{ .Values.auth.database | b64enc }}
