apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon-compute.fullname" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "neon-compute.labels" . | nindent 4 }}
  ports:
  - name: http
    targetPort: http
    protocol: TCP
    port: 80
  - name: pg
    targetPort: pg
    protocol: TCP
    port: 5432
