nameOverride: ""
fullnameOverride: ""

tenantId: ""
timelineId: ""

primary:
  image:
    repository: neondatabase/compute-node-v15
    pullPolicy: Always
    tag: latest
  podAnnotations: {}
  podLabels: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

replica:
  count: 3
  image:
    repository: neondatabase/compute-node-v15
    pullPolicy: Always
    tag: latest
  podAnnotations: {}
  podLabels: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

pageserver:
  host: ""
  port: 5432

safekeepers: []
# - host: ""
#   port: 5454
