nameOverride: ""
fullnameOverride: ""

tenantId: ""
timelineId: ""

image:
  repository: neondatabase/compute-node-v15
  pullPolicy: Always
  tag: latest
podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

pageserver:
  connstring: ""

safekeeper:
  connstrings: []
